version: '3.9'

services:
  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - "${ACTIVEMQ_PORT}:${ACTIVEMQ_PORT}"
      - "8161:8161"

  db:
    image: postgres:latest
    privileged: true
    container_name: database
    restart: always
    ports:
      - "5433:${DB_INTERNAL_PORT}"
    environment:
      POSTGRES_DB: "nexign_project_db"
      POSTGRES_USER: "${DB_PASSWORD}"
      POSTGRES_PASSWORD: "${DB_USERNAME}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  brt-service:
    build:
      context: BRT-service
      dockerfile: Dockerfile
    container_name: brt-service
    env_file:
      - .env
    ports:
      - "${BRT_PORT}:${BRT_PORT}"
    depends_on:
      - db
      - activemq
      - crm-service
      - cdr-service
      - hrs-service
    volumes:
      - ./cdr:/cdr

  cdr-service:
    build:
      context: CDR-service
      dockerfile: Dockerfile
    container_name: cdr-service
    env_file:
      - .env
    ports:
      - "${CDR_PORT}:${CDR_PORT}"
    depends_on:
      - db
    volumes:
      - ./cdr:/cdr

  crm-service:
    build:
      context: CRM-service
      dockerfile: Dockerfile
    container_name: crm-service
    env_file:
      - .env
    ports:
      - "${CRM_PORT}:${CRM_PORT}"
    depends_on:
      - db
      - activemq
      - cdr-service

  hrs-service:
    build:
      context: HRS-service
      dockerfile: Dockerfile
    container_name: hrs-service
    env_file:
      - .env
    ports:
      - "${HRS_PORT}:${HRS_PORT}"
    depends_on:
      - db
      - activemq